### ISSUE TITLE
Add support for HTML emails

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-email-notifications-plugin#10]
Currently code is [commented](https://github.com/killbill/killbill-email-notifications-plugin/blob/e4c20a0999f3edbf7e6793abfe5355bffc315898/src/main/java/org/killbill/billing/plugin/notification/email/EmailSender.java#L84)

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-email-notifications-plugin/pull/32.
