### ISSUE TITLE
Number precision / formatting in templates

### ISSUE THREAD

**Issue by adamlc** [killbill/killbill-email-notifications-plugin#3]
I've been having a play with this plugin but it I've come across an issue, floats seem to be formatted with far too much precision, for example a refund:

```
We have processed a refund in the amount of GBP 937.070000000.
```

I can't seem to figure out a way of doing this in the template, might be worth making sure these are rounded up to 2 decimal places?

**Comment by pierre** [comment]
Could you give https://github.com/killbill/killbill-email-notifications-plugin/commit/5711b2d79c7d7d1d2cf7dfc3212965716ad0747a a try?

Displaying amounts is always tricky as it depends on the currency and the locale. Switching to `formatted*` variables in your template (e.g. `payment.formattedAmount`) should help (make sure to set the locale of your accounts to `en_GB`, see https://github.com/killbill/killbill-email-notifications-plugin/commit/5711b2d79c7d7d1d2cf7dfc3212965716ad0747a#diff-c6d30976a188a6f92ee0e9d8f50a8652R146).

http://docs.killbill.io/0.16/internationalization.html might be relevant.

**Comment by pierre** [comment]
Released in 0.2.1.

A new OSGI export is required though. It will be set [by default](https://github.com/killbill/killbill-platform/commit/8c109da26a4aa97474148d978513c81a8f4c7728) in Kill Bill 0.16.3.

For previous versions, you need to override the property `org.killbill.osgi.system.bundle.export.packages.api` manually and add the missing export `org.killbill.billing.invoice.api.formatters`.

**Comment by husam-otri** [comment]
Thanks for reply @pierre 
 
in order to override the property, i just cloned [git@github.com:killbill/killbill-platform.git](git@github.com:killbill/killbill-platform.git)

then update release.sh (just i commented out some commands which related to git) 
then run _./release.sh_ in order to create new jar files which will include OSGI, but unfortunately i'm getting this compilation error message:


    [INFO] Compiling 5 source files to /home/hussam/qordoba/killbill-platform/platform-api/target/classes
    [INFO] -------------------------------------------------------------
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] /home/hussam/qordoba/killbill-platform/platform-api/src/main/java/org/killbill/billing/platform/api/KillbillService.java:[45,12] class, interface, or enum expected
    [ERROR] /home/hussam/qordoba/killbill-platform/platform-api/src/main/java/org/killbill/billing/platform/api/KillbillService.java:[47,1] class, interface, or enum expected
    [INFO] 2 errors 
    [INFO] -------------------------------------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] killbill-platform .................................. SUCCESS [  6.794 s]
    [INFO] killbill-platform-api .............................. FAILURE [  0.571 s]


am i doing something wrong,  if yes, could you please provide me the steps to override the property?

**Comment by pierre** [comment]
@husam-otri This is a Kill Bill property, you don't have to recompile anything.

Depending on how you start Kill Bill, simply add to your `killbill.properties` file:

```
org.killbill.osgi.system.bundle.export.packages.api=org.killbill.billing.account.api,org.killbill.billing.analytics.api.sanity,org.killbill.billing.analytics.api.user,org.killbill.billing.beatrix.bus.api,org.killbill.billing.catalog.api,org.killbill.billing.catalog.api.rules,org.killbill.billing.invoice.plugin.api,org.killbill.billing.invoice.api,org.killbill.billing.invoice.api.formatters,org.killbill.billing.entitlement.api,org.killbill.billing,org.killbill.clock,org.killbill.billing.notification.api,org.killbill.billing.notification.plugin.api,org.killbill.billing.notification.plugin,org.killbill.billing.osgi.api,org.killbill.billing.osgi.api.config,org.killbill.billing.overdue,org.killbill.billing.payment.api,org.killbill.billing.payment.plugin.api,org.killbill.billing.control.plugin.api,org.killbill.billing.tenant.api,org.killbill.billing.usage.api,org.killbill.billing.util.api,org.killbill.billing.util.nodes,org.killbill.billing.util.audit,org.killbill.billing.util.callcontext,org.killbill.billing.util.customfield,org.killbill.billing.util.email,org.killbill.billing.util.entity,org.killbill.billing.util.tag,org.killbill.billing.util.template,org.killbill.billing.util.template.translation,org.killbill.billing.currency.plugin.api,org.killbill.billing.catalog.plugin.api,org.killbill.billing.entitlement.plugin.api,org.killbill.billing.currency.api,org.killbill.billing.security.api,org.killbill.killbill.osgi.libs.killbill,org.joda.time;org.joda.time.format;version=2.3,org.slf4j;version=1.7.2,org.osgi.service.log;version=1.3,org.osgi.service.http;version=1.2.0,org.osgi.service.deploymentadmin;version=1.1.0,org.osgi.service.event;version=1.2.0
```

or set it on the command line (`-Dorg.killbill.osgi.system.bundle.export.packages.api=...`).
