### ISSUE TITLE
Add supports for TLS

### ISSUE THREAD

**Issue by almasl1** [killbill/killbill-email-notifications-plugin#38]
How do I use TLS? Some email servers (like office 365) only gives you an option of using TLS.  Thanks.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
