### ISSUE TITLE
Support for INVOICE_CREATION event

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-email-notifications-plugin#7]
See https://github.com/killbill/killbill/issues/58.

**Comment by sbrossie** [comment]
@pierre  Not sure i understand what is missing and how this is linked to #58 ?

**Comment by pierre** [comment]
The core functionality being removed is the ability to send emails upon invoice creation, which the plugin doesn't support today (it only supports sending emails for upcoming invoices).
